# ============================================
# 🌐 SpecFlow Selenium - Cross Browser Matrix
# ============================================
# Runs the same test suite across Chrome, Firefox, and Edge in parallel.
# Each job defines its own BROWSER environment variable..
# ============================================

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  HEADLESS: true
  EXECUTION_MODE: PARALLEL
  BASE_URL: "https://the-internet.herokuapp.com"

stages:
- stage: CrossBrowser
  displayName: 🧩 Cross-Browser Test Matrix
  jobs:
  - job: Chrome
    displayName: 🌐 Chrome Tests
    variables:
      BROWSER: chrome
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      - script: dotnet restore
        displayName: Restore Dependencies

      - script: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=chrome.trx"
        displayName: Run Chrome Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/chrome.trx'
          mergeTestResults: true

  - job: Firefox
    displayName: 🦊 Firefox Tests
    variables:
      BROWSER: firefox
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      - script: dotnet restore
        displayName: Restore Dependencies

      - script: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=firefox.trx"
        displayName: Run Firefox Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/firefox.trx'
          mergeTestResults: true

  - job: Edge
    displayName: 🪟 Edge Tests
    variables:
      BROWSER: edge
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      - script: dotnet restore
        displayName: Restore Dependencies

      - script: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=edge.trx"
        displayName: Run Edge Tests

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/edge.trx'
          mergeTestResults: true
