name: Dual-Mode Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # permite ejecución manual

jobs:
  # ==================================
  # JOB AUTOMÁTICO: Parallel Scenarios
  # ==================================
  parallel_tests:
    name: 🧩 Parallel Scenarios (Chrome)
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'  # solo si no es ejecución manual

    env:
      EXECUTION_MODE: PARALLEL
      BROWSERS: chrome
      HEADLESS: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Restore dependencies
        run: dotnet restore SpecFlowSelenium.sln

      - name: Build
        run: dotnet build SpecFlowSelenium.sln --configuration Release --no-restore

      - name: Run tests (Chrome only)
        run: dotnet test SpecFlowSelenium.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: '**/TestResults/*.trx'


  # ==================================
  # JOB MANUAL: Cross-Browser MultiDriver
  # ==================================
  multi_tests:
    name: 🌐 Cross-Browser MultiDriver
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # solo si se lanza manualmente

    env:
      EXECUTION_MODE: MULTI
      BROWSERS: chrome,firefox,edge
      HEADLESS: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Instala navegadores y drivers
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Setup Edge
        uses: browser-actions/setup-edge@v1

      - name: Verificar versiones de drivers
        run: |
          google-chrome --version
          chromedriver --version || echo "⚠️ chromedriver no encontrado"
          firefox --version
          geckodriver --version || echo "⚠️ geckodriver no encontrado"
          microsoft-edge --version
          msedgedriver --version || echo "⚠️ msedgedriver no encontrado"

      - name: Restore dependencies
        run: dotnet restore SpecFlowSelenium.sln

      - name: Build
        run: dotnet build SpecFlowSelenium.sln --configuration Release --no-restore

      - name: Run cross-browser tests
        run: dotnet test SpecFlowSelenium.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: '**/TestResults/*.trx'
